### PR TITLE
my suggested edits

### PR DESCRIPTION
**Pull request by andrewsu**

### CODE REVIEW

**Comment by andrewsu** [comment]
I also think you could shorten the "last remarks" page.  Some of that text is a commentary on the project as a whole, whereas I think the guide could focus more specifically on this specific neo4j application and specifically on the NGLY1 knowledge graph.  (So, for example, de-emphasize the python library, generalizability to other rare diseases, etc.)

**Comment by andrewsu** [comment]
Also, all the output figures are shown with the "Connect result nodes" off, but the default I think is for that to be on.  Please confirm, and if that's correct, might add a line to the instructions...

**Review by NuriaQueralt — APPROVED** [review]

**Review by NuriaQueralt — APPROVED** [review]

**Review by NuriaQueralt — APPROVED** [review]

**Review by NuriaQueralt — APPROVED** [review]
I did use identifiers to both avoid entity ambiguity that the gene symbol could incur and show the use of this attribute in querying.  But i agree that can facilitate the understanding..

**Review by NuriaQueralt — APPROVED** [review]
I merged queries cuz i thought the compression into only one page could facilitate the understanding of the use case, but actually maybe is too dense...

**Comment by NuriaQueralt** [comment]
> I also think you could shorten the "last remarks" page. Some of that text is a commentary on the project as a whole, whereas I think the guide could focus more specifically on this specific neo4j application and specifically on the NGLY1 knowledge graph. (So, for example, de-emphasize the python library, generalizability to other rare diseases, etc.)

**Comment by NuriaQueralt** [comment]
I am gonna shorten the 'last remarks' page de-contextualizing the application from the whole project..

I have a question, what name for the graph do you think is more appropriate: 1) NGLY1 Deficiency KG (emphasizing disease specific domain) or 2) NGLY1 KG (emphasizing disease causing gene centrality)?  My bet is for (1)..

**Comment by NuriaQueralt** [comment]
> I also think you could shorten the "last remarks" page. Some of that text is a commentary on the project as a whole, whereas I think the guide could focus more specifically on this specific neo4j application and specifically on the NGLY1 knowledge graph. (So, for example, de-emphasize the python library, generalizability to other rare diseases, etc.)

I am gonna shorten the 'last remarks' page de-contextualizing the application from the whole project..

I have a question, what name for the graph do you think is more appropriate: 1) NGLY1 Deficiency KG (emphasizing disease specific domain) or 2) NGLY1 KG (emphasizing disease causing gene centrality)? My bet is for (1)..

**Comment by NuriaQueralt** [comment]
> Also, all the output figures are shown with the "Connect result nodes" off, but the default I think is for that to be on. Please confirm, and if that's correct, might add a line to the instructions...

I confirm it.  i am gonna add a line to the instructions..

**Pull request merged**
